apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsd-social-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsd-social
  template:
    metadata:
      labels:
        app: rsd-social
    spec:
      containers:
      - name: rsd-social
        image: nginx:alpine   # Puedes reemplazar por tu imagen propia luego
        ports:
        - containerPort: 80
